### ISSUE TITLE
Write a new Lobby Component that interacts with the Server API

### ISSUE THREAD

**Issue by rezende** [rezende/scythe-bidder#12]
The Lobby component is a external dependency and can't be easily modified. Write a new Lobby page that interacts with the Server API. 

BG.io has a LobbyClient library that makes it easier to call the endpoints: https://boardgame.io/documentation/#/api/Lobby (under Plain JS)

**Comment by erinoerin** [comment]
Does this mean you're (re)creating the UI from scratch?

**Comment by erinoerin** [comment]
[I mocked up a couple of lobby layouts](https://www.figma.com/file/3jI0J3NzC6y7rp5T4HgaDs/Scythe-Auction?node-id=11%3A14). 

- No more entering and exiting the lobby buttons. User enters the lobby when their player id is created/changes. User exits and re-enters the lobby when they change their player name
- Add React Boostrap Styling
- Add control to indicate IFA support (it makes the most sense to me to control this at game creation rather than in game)

**Comment by lightyearsaway** [comment]
These are really nice! I'd love to help out with implementing this.

**Comment by lightyearsaway** [comment]
Done in #27
